name: Publish Vite Package to GitHub Packages

on:
  push:
    branches: ["main"]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  packages: write
  id-token: write

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
          scope: "@izumiano"
      - run: npm ci
        env:
          # Use GITHUB_TOKEN for authentication
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm test
      - run: npm run build
      - run: mv package.json LICENCE dist/
      - uses: actions/upload-artifact@v5
        with:
          name: package-artifact
          path: dist

  publish-package:
    runs-on: ubuntu-latest
    needs: build-package
    permissions:
      contents: read
      packages: write # Grant write access to packages
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: package-artifact
          path: . # Download artifact to current directory
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
          scope: "@izumiano"
      - run: npm ci
        env:
          # Use GITHUB_TOKEN for authentication
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm test
      - run: npm run build:example
      - uses: actions/upload-artifact@v5
        with:
          name: example-artifact
          path: dist

  deploy-pages:
    needs: build-example
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: example-artifact
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: "github-pages"
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4